### ISSUE TITLE
Balance Gauge

### ISSUE THREAD

**Issue by Xargot** [zacharied/FFXIV-Plugin-HudManager#20] opened 2022-03-19 22:15 UTC
Balance Gauge disappears when switching from Redmage to any other job. You have to go into Hudmanager and disable and enable to see it again. If I uninstall the Hudmanager completely, I can't turn it back on at all, even using FF14's layouts.

**Comment by zacharied** [comment] 2022-03-30 23:06
Sorry for the delay, I was taking a break. I'm actually not able to reproduce this bug. Would you mind sending me your config at `%AppData%\XIVLauncher\pluginConfigs\HUDManager.json`?

**Comment by nebel** [comment] 2023-09-09 23:42
Closing as this issue is quite old and has not been reported by anyone else for some time, so I assume it is likely fixed. If this is still happening, please let me know.

**Closed by nebel** 2023-09-09 23:42 UTC
Labels: bug, cannot repro
